//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AP3_GestionHackathon
{
    using System;
    using System.Collections.Generic;
    
    public partial class participer
    {
        public int id_activite { get; set; }
        public int id_conferencier { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
    
        public virtual atelier atelier { get; set; }
        public virtual conferencier conferencier { get; set; }
    }
}
